services:
  - type: web
    name: banger-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://banger-server.onrender.com/api

